### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by srgloureiro** [StepS-/wkReSolution#1]
I see it like this
http://i.imgur.com/uv2Ivby.png
(task manager should not be in the picture but you got the idea)
and it is stuck!

Other times I see the starting screens in a red'ish way.; like if there was black & red TV.

My computer is http://www.globaldata.pt/portatil-msi-15-6-gl62-6qf-1001xpt.html and running Windows 10.

**Comment by StepS-** [comment]
Hi @srgloureiro. Sorry for the delayed reply. You're running ReSolution with windowed mode, right? That white-window issue was supposed to be fixed many years ago. I haven't seen it occur for a long time. Are you sure that no settings are changed? What if you try different resolutions?
P.S.: this is not directly related to ReSolution, as it's a bug of the original game that ReSolution itself doesn't affect, but I'd still like to help you resolve this.
