### ISSUE TITLE
Sorry, but your Worms2.exe version, has to be 1.05 for wkResolution to work. Please patch your game to 1.05 and try again.

### ISSUE THREAD

**Issue by MrSopaipilla** [StepS-/wkReSolution#3]
![Captura de pantalla 2024-04-05 160233](https://github.com/StepS-/wkReSolution/assets/65387124/3b8a55b7-fd3a-42b8-8b8b-30f50e174190)

I don't understand this error, what am I wrong?

What am I doing wrong?

**is Worms Armaggedon Steam version**

**Comment by MrSopaipilla** [comment]
[wkReSolution 0.3.2](https://github.com/StepS-/wkReSolution/releases/tag/0.3.2)

That's the version I'm trying to install

**Comment by Carlmundo** [comment]
As the description says, this is for Worms 2 and World Party. It's not for Armageddon.
